"use client";

import { Button } from "@/components/ui/button";
import { CustomProgress } from "@/components/ui/custom-progress";
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ClipboardList, Download, X } from "lucide-react";

interface ScorecardModalProps {
  isOpen: boolean;
  onClose: () => void;
}

interface CompetencyScore {
  id: string;
  name: string;
  score: number;
  description: string;
}

export default function ScorecardModal({ isOpen, onClose }: ScorecardModalProps) {
  // Mock data for the sample scorecard
  const candidateData = {
    candidateName: "Alex Thompson",
    position: "Senior Product Manager",
    interviewDate: "14 May 2024",
    duration: "32 minutes",
    overallScore: 83,
    strengths: [
      { id: "strength-1", text: "Strategic thinking and product vision" },
      { id: "strength-2", text: "Communication of complex ideas" },
      { id: "strength-3", text: "Stakeholder management experience" },
    ],
    areasForImprovement: [
      { id: "area-1", text: "Technical knowledge of development processes" },
      { id: "area-2", text: "Quantitative analysis depth" },
    ],
    competencies: [
      {
        id: "comp-strategy",
        name: "Product Strategy",
        score: 87,
        description: "Demonstrates strong product vision and market awareness.",
      },
      {
        id: "comp-stakeholder",
        name: "Stakeholder Management",
        score: 92,
        description: "Excellent at managing diverse stakeholder expectations.",
      },
      {
        id: "comp-technical",
        name: "Technical Understanding",
        score: 68,
        description: "Basic grasp of development processes with some gaps.",
      },
      {
        id: "comp-data",
        name: "Data-Driven Decision Making",
        score: 76,
        description: "Uses data effectively but could deepen analytical skills.",
      },
      {
        id: "comp-leadership",
        name: "Cross-Functional Leadership",
        score: 88,
        description: "Works effectively across engineering, design, and marketing.",
      },
    ],
    interviewerNotes:
      "Alex demonstrated strong leadership qualities and clear communication throughout the interview. Their experience managing complex product launches was particularly impressive. While their technical knowledge has some gaps, they showed a willingness to learn and collaborate with technical teams.",
  };

  // Helper function to determine score color
  const getScoreColor = (score: number) => {
    if (score >= 85) return "text-green-600 dark:text-green-400";
    if (score >= 70) return "text-amber-600 dark:text-amber-400";
    return "text-red-600 dark:text-red-400";
  };

  // Helper function to determine progress color
  const getProgressColor = (score: number) => {
    if (score >= 85) return "bg-green-600 dark:bg-green-500";
    if (score >= 70) return "bg-amber-600 dark:bg-amber-500";
    return "bg-red-600 dark:bg-red-500";
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-3xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-2xl flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-primary" />
            Candidate Assessment Report
          </DialogTitle>
          <DialogDescription>
            Sample interview scorecard generated by Interview Optimiser AI
          </DialogDescription>
        </DialogHeader>

        <DialogClose className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
          <X className="h-4 w-4" />
          <span className="sr-only">Close</span>
        </DialogClose>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Candidate Information */}
          <div className="bg-muted/30 rounded-lg p-4 space-y-3">
            <h3 className="font-semibold text-lg">Candidate Information</h3>
            <div className="grid grid-cols-2 gap-x-3 gap-y-1.5">
              <div className="text-sm text-muted-foreground">Name:</div>
              <div className="text-sm font-medium">{candidateData.candidateName}</div>
              <div className="text-sm text-muted-foreground">Position:</div>
              <div className="text-sm font-medium">{candidateData.position}</div>
              <div className="text-sm text-muted-foreground">Interview Date:</div>
              <div className="text-sm font-medium">{candidateData.interviewDate}</div>
              <div className="text-sm text-muted-foreground">Duration:</div>
              <div className="text-sm font-medium">{candidateData.duration}</div>
            </div>
          </div>

          {/* Overall Score */}
          <div className="bg-muted/30 rounded-lg p-4 flex flex-col items-center justify-center">
            <h3 className="font-semibold text-lg mb-3">Overall Evaluation</h3>
            <div className={`text-5xl font-bold ${getScoreColor(candidateData.overallScore)}`}>
              {candidateData.overallScore}%
            </div>
            <div className="mt-2 text-sm">
              {candidateData.overallScore >= 85
                ? "Strong Candidate"
                : candidateData.overallScore >= 70
                  ? "Potential Candidate"
                  : "Needs Development"}
            </div>
          </div>
        </div>

        {/* Competency Scores */}
        <div className="space-y-4">
          <h3 className="font-semibold text-lg">Competency Assessment</h3>
          {candidateData.competencies.map((competency) => (
            <CompetencyScoreCard key={competency.id} competency={competency} />
          ))}
        </div>

        {/* Strengths and Areas for Improvement */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-2">
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Key Strengths</h3>
            <ul className="list-disc pl-5 space-y-1">
              {candidateData.strengths.map((strength) => (
                <li key={strength.id} className="text-sm">
                  {strength.text}
                </li>
              ))}
            </ul>
          </div>
          <div className="space-y-2">
            <h3 className="font-semibold text-lg">Areas for Improvement</h3>
            <ul className="list-disc pl-5 space-y-1">
              {candidateData.areasForImprovement.map((area) => (
                <li key={area.id} className="text-sm">
                  {area.text}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Additional Notes */}
        <div className="space-y-2 mt-2">
          <h3 className="font-semibold text-lg">Interviewer Notes</h3>
          <p className="text-sm bg-muted/30 p-3 rounded-md italic">
            {candidateData.interviewerNotes}
          </p>
        </div>

        <DialogFooter className="flex-col sm:flex-row gap-2 sm:gap-0">
          <div className="text-xs text-muted-foreground">
            This is a sample report with mock data for demonstration purposes only.
          </div>
          <Button variant="outline" className="gap-2" onClick={onClose}>
            <Download className="h-4 w-4" /> Download Sample PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// Sub-component for displaying individual competency scores
function CompetencyScoreCard({ competency }: { competency: CompetencyScore }) {
  const getProgressColor = (score: number) => {
    if (score >= 85) return "bg-green-600 dark:bg-green-500";
    if (score >= 70) return "bg-amber-600 dark:bg-amber-500";
    return "bg-red-600 dark:bg-red-500";
  };

  return (
    <div className="bg-muted/30 rounded-lg p-4">
      <div className="flex justify-between items-center mb-2">
        <h4 className="font-medium">{competency.name}</h4>
        <span
          className={`font-semibold ${
            competency.score >= 85
              ? "text-green-600 dark:text-green-400"
              : competency.score >= 70
                ? "text-amber-600 dark:text-amber-400"
                : "text-red-600 dark:text-red-400"
          }`}
        >
          {competency.score}%
        </span>
      </div>
      <CustomProgress
        value={competency.score}
        className="h-2"
        indicatorClassName={getProgressColor(competency.score)}
      />
      <p className="text-sm text-muted-foreground mt-2">{competency.description}</p>
    </div>
  );
}
