import * as Sentry from "@sentry/nextjs";
import HTMLtoDOCX from "html-to-docx";
import { type NextRequest, NextResponse } from "next/server";
import { css } from "@/lib/export-css";
import { getFontFamilyName } from "@/lib/fontUtils";
import { formatErrorEntity } from "@/lib/utils/formatEntity";
import { config } from "~/config";
import { logger } from "~/lib/logger";

export const runtime = "nodejs";

export async function POST(req: NextRequest) {
  try {
    logger.info({ event: "generate-docx" }, "Generating DOCX");
    const { htmlContent, paperSize, margin, bodyFont, headingFont } = await req.json();

    if (!htmlContent) {
      logger.error({ event: "generate-docx" }, "HTML content is required");
      return NextResponse.json({ error: "HTML content is required" }, { status: 400 });
    }

    // Compile Tailwind CSS
    logger.info("Compiling Tailwind CSS");

    const htmlContentWithStyles = htmlContent.replace("{{css_placeholder}}", css);

    logger.info("HTML content with styles");

    const bodyFontFamilyName = getFontFamilyName(bodyFont);
    const headingFontFamilyName = getFontFamilyName(headingFont);

    logger.info({ event: "generate-docx" }, "Converting HTML to DOCX");

    const docxBuffer = await HTMLtoDOCX(htmlContentWithStyles, "", {
      orientation: "portrait",
      pageSize: {
        width: paperSize.width,
        height: paperSize.height,
      },
      margins: {
        top: margin * 56.7,
        right: margin * 56.7,
        bottom: margin * 56.7,
        left: margin * 56.7,
      },
      createdAt: new Date(),
      lastModified: new Date(),
      description: `Document generated by ${config.projectName} (${config.baseUrl})`,
      font: bodyFontFamilyName,
      styles: {
        heading1: {
          font: headingFontFamilyName,
        },
        heading2: {
          font: headingFontFamilyName,
        },
        heading3: {
          font: headingFontFamilyName,
        },
        heading4: {
          font: headingFontFamilyName,
        },
        heading5: {
          font: headingFontFamilyName,
        },
        heading6: {
          font: headingFontFamilyName,
        },
      },
      creator: `${config.projectName} (${config.baseUrl})`,
    });

    logger.info({ event: "generate-docx" }, "Converting blob to ArrayBuffer");
    const arrayBuffer = docxBuffer;

    logger.info({ event: "generate-docx" }, "Creating Response with DOCX file");
    return new NextResponse(arrayBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": 'attachment; filename="document.docx"',
      },
    });
  } catch (error) {
    Sentry.withScope((scope) => {
      scope.setExtra("context", "POST /api/generate-docx");
      scope.setExtra("error", error);
      Sentry.captureException(error);
    });
    logger.error(
      {
        message: error instanceof Error ? error.message : "Unknown error",
        error,
      },
      "Error generating DOCX"
    );
    return NextResponse.json(formatErrorEntity("Internal server error"), {
      status: 500,
    });
  }
}
