name: DB Migrations

on:
  push:
    branches: [main, dev, qa]
  pull_request:
    branches: [main, dev, qa]

permissions:
  contents: write
  pull-requests: write

jobs:
  db-migrations:
    name: DB Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: bun install

      - name: Generate Migrations
        run: bun db generate

      - name: Deploy Database Migrations
        run: bun db:migrate:prd
