name: Deploy Lambda on Dev Merge

on:
  push:
    branches:
      - dev

jobs:
  deploy-lambdas:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install deps
        run: bun install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Build and apply lambdas
        run: |
          bun run tfa
        env:
          TF_VAR_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          TF_VAR_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
